-- Stage Flow database notice
--
-- DO NOT use this file to provision Stage Flow.
-- The authoritative database history is in:
--   supabase/migrations/
--
-- Stage Flow now uses a normalized, RLS-protected multi-user core:
-- organisations/staff, organisation settings, recurring session templates,
-- learners, dated session occurrences, attendance, assessment history/current
-- progress, learner measurements, learner notes, and per-session notes.
--
-- Apply migrations in timestamp order or use the connected Supabase project.
