-- Stage Flow database notice
--
-- DO NOT use this file to provision Stage Flow.
-- It was originally an early schema draft and is intentionally kept as a
-- harmless pointer so old links do not run an obsolete database design.
--
-- The authoritative database history is:
--   supabase/migrations/
--
-- Apply migrations in timestamp order, or use the connected Supabase project.
-- Current production tables include organisation/account foundations and the
-- RLS-protected organisation workspace.
